// Seed directory for the categories the legacy datasets never covered
// (finance, education, healthcare, safety, transport, airports, sports…).
//
// These are real, well-known Rwandan institutions rather than invented
// listings, but they are a DEMO SEED, not a verified dataset:
//   - located to district only, so every entry renders with the "~"
//     approximate-distance treatment
//   - no ratings, phone numbers or opening hours are asserted, because we
//     don't have them
// Verify against an authoritative source before treating this as production
// data. Adding a row is enough to make it appear everywhere — search, map,
// category pages and the sidebar counts all read from the same catalog.

export interface DirectoryRow {
  name: string;
  /** Category group id from lib/places/taxonomy.ts. */
  group: string;
  /** Must be one of that group's subcategories. */
  subcategory: string;
  /** District. */
  district: string;
  /** Neighbourhood or sector, when it is well known. */
  area?: string;
  description?: string;
}

export const DIRECTORY_ROWS: DirectoryRow[] = [
  /* ------------------------------------------------------------ finance */
  { name: "Bank of Kigali Headquarters", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre", description: "Rwanda's largest commercial bank by assets." },
  { name: "National Bank of Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre", description: "The country's central bank and financial regulator." },
  { name: "I&M Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Equity Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Bank of Africa Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Access Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Ecobank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "KCB Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "BPR Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "NCBA Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Guaranty Trust Bank Rwanda", group: "finance", subcategory: "Banks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Development Bank of Rwanda", group: "finance", subcategory: "Banks", district: "Gasabo", area: "Kacyiru", description: "Rwanda's national development finance institution." },
  { name: "Bank of Kigali ATM — Kigali Heights", group: "finance", subcategory: "ATMs", district: "Gasabo", area: "Kimihurura" },
  { name: "Bank of Kigali ATM — Nyabugogo", group: "finance", subcategory: "ATMs", district: "Nyarugenge", area: "Nyabugogo" },
  { name: "Equity Bank ATM — Kigali City Tower", group: "finance", subcategory: "ATMs", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "I&M Bank ATM — Remera", group: "finance", subcategory: "ATMs", district: "Gasabo", area: "Remera" },
  { name: "KCB Bank ATM — Kimironko", group: "finance", subcategory: "ATMs", district: "Gasabo", area: "Kimironko" },
  { name: "Ecobank ATM — Kigali International Airport", group: "finance", subcategory: "ATMs", district: "Kicukiro", area: "Kanombe" },
  { name: "Bank of Kigali ATM — Musanze", group: "finance", subcategory: "ATMs", district: "Musanze" },
  { name: "Urwego Bank", group: "finance", subcategory: "Microfinance Institutions", district: "Nyarugenge", description: "Microfinance bank focused on low-income households." },
  { name: "Unguka Bank", group: "finance", subcategory: "Microfinance Institutions", district: "Nyarugenge" },
  { name: "Duterimbere IMF", group: "finance", subcategory: "Microfinance Institutions", district: "Nyarugenge" },
  { name: "Vision Finance Company", group: "finance", subcategory: "Microfinance Institutions", district: "Nyarugenge" },
  { name: "Umurenge SACCO — Remera", group: "finance", subcategory: "Microfinance Institutions", district: "Gasabo", area: "Remera", description: "Sector-level savings and credit cooperative." },
  { name: "Umurenge SACCO — Kicukiro", group: "finance", subcategory: "Microfinance Institutions", district: "Kicukiro" },
  { name: "MTN MoMo Service Centre — Kigali", group: "finance", subcategory: "Mobile Money", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "MTN Rwanda Headquarters", group: "finance", subcategory: "Mobile Money", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Airtel Money Service Centre — Kigali", group: "finance", subcategory: "Mobile Money", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Airtel Rwanda Service Centre — Remera", group: "finance", subcategory: "Mobile Money", district: "Gasabo", area: "Remera" },

  /* ---------------------------------------------------------- education */
  { name: "University of Rwanda — College of Science and Technology", group: "education", subcategory: "Universities", district: "Nyarugenge", area: "Nyarugenge Campus" },
  { name: "University of Rwanda — Huye Campus", group: "education", subcategory: "Universities", district: "Huye", description: "The country's oldest university campus." },
  { name: "University of Rwanda — Remera Campus", group: "education", subcategory: "Universities", district: "Gasabo", area: "Remera" },
  { name: "University of Rwanda — Busogo Campus", group: "education", subcategory: "Universities", district: "Musanze" },
  { name: "University of Rwanda — Nyagatare Campus", group: "education", subcategory: "Universities", district: "Nyagatare" },
  { name: "African Leadership University", group: "education", subcategory: "Universities", district: "Gasabo", area: "Bumbogo" },
  { name: "Carnegie Mellon University Africa", group: "education", subcategory: "Universities", district: "Gasabo", area: "Kigali Innovation City" },
  { name: "Adventist University of Central Africa", group: "education", subcategory: "Universities", district: "Gasabo", area: "Gishushu" },
  { name: "Kigali Independent University (ULK)", group: "education", subcategory: "Universities", district: "Gasabo", area: "Gisozi" },
  { name: "University of Kigali", group: "education", subcategory: "Universities", district: "Kicukiro" },
  { name: "Mount Kenya University Rwanda", group: "education", subcategory: "Universities", district: "Kicukiro" },
  { name: "INES-Ruhengeri", group: "education", subcategory: "Universities", district: "Musanze" },
  { name: "University of Global Health Equity", group: "education", subcategory: "Universities", district: "Burera", area: "Butaro" },
  { name: "Protestant Institute of Arts and Social Sciences", group: "education", subcategory: "Universities", district: "Huye" },
  { name: "IPRC Kigali", group: "education", subcategory: "Colleges", district: "Kicukiro", description: "Rwanda Polytechnic's Kigali integrated polytechnic college." },
  { name: "IPRC Musanze", group: "education", subcategory: "Colleges", district: "Musanze" },
  { name: "IPRC Huye", group: "education", subcategory: "Colleges", district: "Huye" },
  { name: "IPRC Karongi", group: "education", subcategory: "Colleges", district: "Karongi" },
  { name: "Rwanda Coding Academy", group: "education", subcategory: "Training Centers", district: "Nyabihu" },
  { name: "Kepler Kigali", group: "education", subcategory: "Training Centers", district: "Kicukiro" },
  { name: "Rwanda Institute for Conservation Agriculture", group: "education", subcategory: "Training Centers", district: "Bugesera" },
  { name: "Green Hills Academy", group: "education", subcategory: "Schools", district: "Gasabo", area: "Nyarutarama" },
  { name: "Kigali International Community School", group: "education", subcategory: "Schools", district: "Gasabo", area: "Kagugu" },
  { name: "École Belge de Kigali", group: "education", subcategory: "Schools", district: "Gasabo" },
  { name: "Lycée de Kigali", group: "education", subcategory: "Schools", district: "Nyarugenge" },
  { name: "Riviera High School", group: "education", subcategory: "Schools", district: "Gasabo" },
  { name: "Gashora Girls Academy of Science and Technology", group: "education", subcategory: "Schools", district: "Bugesera" },
  { name: "Groupe Scolaire Officiel de Butare", group: "education", subcategory: "Schools", district: "Huye" },
  { name: "Kigali Public Library", group: "education", subcategory: "Libraries", district: "Gasabo", area: "Kacyiru", description: "Rwanda's national public library." },
  { name: "University of Rwanda Library — Huye", group: "education", subcategory: "Libraries", district: "Huye" },

  /* ----------------------------------------------------------- health */
  { name: "King Faisal Hospital", group: "health", subcategory: "Hospitals", district: "Gasabo", area: "Kacyiru", description: "Rwanda's main referral and specialist hospital." },
  { name: "University Teaching Hospital of Kigali (CHUK)", group: "health", subcategory: "Hospitals", district: "Nyarugenge", description: "The largest public referral hospital in the country." },
  { name: "University Teaching Hospital of Butare (CHUB)", group: "health", subcategory: "Hospitals", district: "Huye" },
  { name: "Rwanda Military Hospital", group: "health", subcategory: "Hospitals", district: "Kicukiro", area: "Kanombe" },
  { name: "Kibagabaga District Hospital", group: "health", subcategory: "Hospitals", district: "Gasabo", area: "Kibagabaga" },
  { name: "Masaka District Hospital", group: "health", subcategory: "Hospitals", district: "Kicukiro" },
  { name: "Muhima District Hospital", group: "health", subcategory: "Hospitals", district: "Nyarugenge", area: "Muhima" },
  { name: "Kacyiru District Hospital", group: "health", subcategory: "Hospitals", district: "Gasabo", area: "Kacyiru" },
  { name: "Baho International Hospital", group: "health", subcategory: "Hospitals", district: "Gasabo" },
  { name: "La Croix du Sud Hospital", group: "health", subcategory: "Hospitals", district: "Gasabo", area: "Remera" },
  { name: "Butaro District Hospital", group: "health", subcategory: "Hospitals", district: "Burera", area: "Butaro" },
  { name: "Ruhengeri Referral Hospital", group: "health", subcategory: "Hospitals", district: "Musanze" },
  { name: "Kibuye Referral Hospital", group: "health", subcategory: "Hospitals", district: "Karongi" },
  { name: "Rwinkwavu District Hospital", group: "health", subcategory: "Hospitals", district: "Kayonza" },
  { name: "Nyagatare District Hospital", group: "health", subcategory: "Hospitals", district: "Nyagatare" },
  { name: "Legacy Clinics", group: "health", subcategory: "Clinics", district: "Gasabo", area: "Kimihurura" },
  { name: "Polyclinique du Plateau", group: "health", subcategory: "Clinics", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Doctors' Plaza", group: "health", subcategory: "Clinics", district: "Gasabo", area: "Remera" },
  { name: "Kigali Adventist Medical Centre", group: "health", subcategory: "Clinics", district: "Gasabo" },
  { name: "King Faisal Hospital Pharmacy", group: "health", subcategory: "Pharmacies", district: "Gasabo", area: "Kacyiru" },
  { name: "CHUK Hospital Pharmacy", group: "health", subcategory: "Pharmacies", district: "Nyarugenge" },
  { name: "Kibagabaga Hospital Pharmacy", group: "health", subcategory: "Pharmacies", district: "Gasabo" },
  { name: "Ruhengeri Hospital Pharmacy", group: "health", subcategory: "Pharmacies", district: "Musanze" },
  { name: "Remera Health Center", group: "health", subcategory: "Health Centers", district: "Gasabo", area: "Remera" },
  { name: "Kimironko Health Center", group: "health", subcategory: "Health Centers", district: "Gasabo", area: "Kimironko" },
  { name: "Nyamirambo Health Center", group: "health", subcategory: "Health Centers", district: "Nyarugenge", area: "Nyamirambo" },
  { name: "Gikondo Health Center", group: "health", subcategory: "Health Centers", district: "Kicukiro", area: "Gikondo" },
  { name: "Kinyinya Health Center", group: "health", subcategory: "Health Centers", district: "Gasabo", area: "Kinyinya" },

  /* ----------------------------------------------------------- safety */
  { name: "Rwanda National Police Headquarters", group: "safety", subcategory: "Police Stations", district: "Gasabo", area: "Kacyiru" },
  { name: "Remera Police Station", group: "safety", subcategory: "Police Stations", district: "Gasabo", area: "Remera" },
  { name: "Nyamirambo Police Station", group: "safety", subcategory: "Police Stations", district: "Nyarugenge", area: "Nyamirambo" },
  { name: "Kicukiro Police Station", group: "safety", subcategory: "Police Stations", district: "Kicukiro" },
  { name: "Gisozi Police Station", group: "safety", subcategory: "Police Stations", district: "Gasabo", area: "Gisozi" },
  { name: "Musanze Police Station", group: "safety", subcategory: "Police Stations", district: "Musanze" },
  { name: "Rubavu Police Station", group: "safety", subcategory: "Police Stations", district: "Rubavu" },
  { name: "Huye Police Station", group: "safety", subcategory: "Police Stations", district: "Huye" },
  { name: "Muhanga Police Station", group: "safety", subcategory: "Police Stations", district: "Muhanga" },
  { name: "Rwanda National Police Fire and Rescue Brigade", group: "safety", subcategory: "Fire Stations", district: "Gasabo", area: "Kacyiru" },
  { name: "Kigali City Fire Station", group: "safety", subcategory: "Fire Stations", district: "Nyarugenge" },
  { name: "Musanze Fire Station", group: "safety", subcategory: "Fire Stations", district: "Musanze" },
  { name: "SAMU Rwanda — Pre-hospital Emergency Service", group: "safety", subcategory: "Emergency Services", district: "Nyarugenge", description: "National ambulance service, reachable on 912." },
  { name: "Rwanda Emergency Call Centre (112)", group: "safety", subcategory: "Emergency Services", district: "Gasabo", area: "Kacyiru" },
  { name: "Rwanda Red Cross Society", group: "safety", subcategory: "Emergency Services", district: "Nyarugenge" },

  /* -------------------------------------------------------- transport */
  { name: "Nyabugogo Bus Terminal", group: "transport", subcategory: "Bus Stations", district: "Nyarugenge", area: "Nyabugogo", description: "Rwanda's busiest intercity bus terminal." },
  { name: "Remera Bus Park", group: "transport", subcategory: "Bus Stations", district: "Gasabo", area: "Remera" },
  { name: "Kimironko Bus Park", group: "transport", subcategory: "Bus Stations", district: "Gasabo", area: "Kimironko" },
  { name: "Musanze Bus Park", group: "transport", subcategory: "Bus Stations", district: "Musanze" },
  { name: "Huye Bus Park", group: "transport", subcategory: "Bus Stations", district: "Huye" },
  { name: "Rubavu Bus Park", group: "transport", subcategory: "Bus Stations", district: "Rubavu" },
  { name: "Rusizi Bus Park", group: "transport", subcategory: "Bus Stations", district: "Rusizi" },
  { name: "Nyabugogo Taxi Park", group: "transport", subcategory: "Transport Hubs", district: "Nyarugenge", area: "Nyabugogo" },
  { name: "Downtown Taxi Park", group: "transport", subcategory: "Transport Hubs", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Volcano Express — Nyabugogo", group: "transport", subcategory: "Transport Hubs", district: "Nyarugenge", area: "Nyabugogo" },
  { name: "Ritco Ltd — Nyabugogo", group: "transport", subcategory: "Transport Hubs", district: "Nyarugenge", area: "Nyabugogo" },
  { name: "Horizon Express — Nyabugogo", group: "transport", subcategory: "Transport Hubs", district: "Nyarugenge", area: "Nyabugogo" },
  { name: "Remera Taxi Stand", group: "transport", subcategory: "Taxi Stands", district: "Gasabo", area: "Remera" },
  { name: "Kimironko Taxi Stand", group: "transport", subcategory: "Taxi Stands", district: "Gasabo", area: "Kimironko" },
  { name: "Kacyiru Taxi Stand", group: "transport", subcategory: "Taxi Stands", district: "Gasabo", area: "Kacyiru" },
  { name: "Nyamirambo Taxi Stand", group: "transport", subcategory: "Taxi Stands", district: "Nyarugenge", area: "Nyamirambo" },
  { name: "Car Rental Desks — Kigali International Airport", group: "transport", subcategory: "Car Rental", district: "Kicukiro", area: "Kanombe" },
  { name: "Kigali City Centre Car Hire", group: "transport", subcategory: "Car Rental", district: "Nyarugenge", area: "Kigali City Centre" },

  /* --------------------------------------------------------- airports */
  { name: "Kigali International Airport", group: "airports", subcategory: "International Airports", district: "Kicukiro", area: "Kanombe", description: "Rwanda's main international gateway." },
  { name: "Kamembe International Airport", group: "airports", subcategory: "International Airports", district: "Rusizi", description: "Serves the south-west and the Lake Kivu shore." },
  { name: "Bugesera International Airport", group: "airports", subcategory: "International Airports", district: "Bugesera", description: "Under construction as Rwanda's future main airport." },
  { name: "Gisenyi Airport", group: "airports", subcategory: "Domestic Airports", district: "Rubavu" },
  { name: "Huye Airport", group: "airports", subcategory: "Domestic Airports", district: "Huye" },
  { name: "Ruhengeri Airstrip", group: "airports", subcategory: "Airstrips", district: "Musanze" },
  { name: "Nemba Airstrip", group: "airports", subcategory: "Airstrips", district: "Gakenke" },

  /* ------------------------------------------------------------- arts */
  { name: "Rwanda Art Museum", group: "arts", subcategory: "Museums", district: "Kicukiro", area: "Kanombe", description: "Contemporary art in the former presidential palace." },
  { name: "Museum of Environment", group: "arts", subcategory: "Museums", district: "Karongi" },
  { name: "Rwesero Art Museum", group: "arts", subcategory: "Museums", district: "Nyanza" },
  { name: "National Liberation Museum Park", group: "arts", subcategory: "Museums", district: "Gicumbi", area: "Mulindi" },
  { name: "Niyo Art Gallery", group: "arts", subcategory: "Art Galleries", district: "Gasabo", area: "Kacyiru" },
  { name: "Ivuka Arts Kigali", group: "arts", subcategory: "Art Galleries", district: "Gasabo", area: "Kacyiru" },
  { name: "Uburanga Arts Studio", group: "arts", subcategory: "Art Spaces", district: "Gasabo" },
  { name: "Impact Hub Kigali", group: "arts", subcategory: "Art Spaces", district: "Gasabo", area: "Kiyovu" },
  { name: "Institut Français du Rwanda", group: "arts", subcategory: "Cultural Centers", district: "Gasabo", area: "Kacyiru" },
  { name: "Goethe-Institut Kigali", group: "arts", subcategory: "Cultural Centers", district: "Gasabo" },
  { name: "Rwanda Cultural Heritage Academy", group: "arts", subcategory: "Cultural Centers", district: "Nyanza" },
  { name: "Kigali Cultural Village", group: "arts", subcategory: "Cultural Centers", district: "Gasabo", area: "Kimihurura" },

  /* -------------------------------------------------------- memorials */
  { name: "Nyamata Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Bugesera", area: "Nyamata" },
  { name: "Ntarama Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Bugesera", area: "Ntarama" },
  { name: "Bisesero Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Karongi" },
  { name: "Nyarubuye Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Kirehe" },
  { name: "Rebero Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Kicukiro", area: "Rebero" },
  { name: "Nyanza-Kicukiro Genocide Memorial", group: "memorials", subcategory: "Genocide Memorials", district: "Kicukiro" },
  { name: "Belgian Peacekeepers Memorial", group: "memorials", subcategory: "Memorial Sites", district: "Nyarugenge", area: "Camp Kigali" },
  { name: "Royal Tombs of Mwima", group: "memorials", subcategory: "Historical Sites", district: "Nyanza" },
  { name: "Rukari — Ancient Royal Residence", group: "memorials", subcategory: "Historical Sites", district: "Nyanza" },
  { name: "Nyungwe Forest Heritage Site", group: "memorials", subcategory: "Heritage Sites", district: "Nyamagabe", description: "One of Africa's oldest montane rainforests." },
  { name: "Volcanoes National Park Heritage Site", group: "memorials", subcategory: "Heritage Sites", district: "Musanze" },

  /* ----------------------------------------------------------- sports */
  { name: "Amahoro National Stadium", group: "sports", subcategory: "Stadiums", district: "Gasabo", area: "Remera", description: "Rwanda's national stadium." },
  { name: "Kigali Pelé Stadium", group: "sports", subcategory: "Stadiums", district: "Nyarugenge", area: "Nyamirambo" },
  { name: "Huye Stadium", group: "sports", subcategory: "Stadiums", district: "Huye" },
  { name: "Umuganda Stadium", group: "sports", subcategory: "Stadiums", district: "Rubavu" },
  { name: "Kicukiro Stadium", group: "sports", subcategory: "Stadiums", district: "Kicukiro" },
  { name: "Bugesera Stadium", group: "sports", subcategory: "Stadiums", district: "Bugesera" },
  { name: "Nyagatare Stadium", group: "sports", subcategory: "Stadiums", district: "Nyagatare" },
  { name: "Kigali Golf Club", group: "sports", subcategory: "Sports Grounds", district: "Gasabo", area: "Nyarutarama" },
  { name: "Cercle Sportif de Kigali", group: "sports", subcategory: "Sports Grounds", district: "Nyarugenge" },
  { name: "Petit Stade Remera", group: "sports", subcategory: "Sports Grounds", district: "Gasabo", area: "Remera" },
  { name: "Kigali Convention Centre", group: "sports", subcategory: "Event Venues", district: "Gasabo", area: "Kimihurura", description: "Landmark conference venue and Kigali's most recognisable building." },
  { name: "Gikondo Expo Grounds", group: "sports", subcategory: "Event Venues", district: "Kicukiro", area: "Gikondo", description: "Home of the Rwanda International Trade Fair." },
  { name: "Camp Kigali Grounds", group: "sports", subcategory: "Event Venues", district: "Nyarugenge" },

  /* ------------------------------------------------------- recreation */
  { name: "Club Rafiki", group: "recreation", subcategory: "Sports Clubs", district: "Nyarugenge", area: "Nyamirambo", description: "Community youth sports and skills centre." },
  { name: "Cercle Sportif de Kigali Pool", group: "recreation", subcategory: "Swimming Pools", district: "Nyarugenge" },
  { name: "Nyarutarama Sports Club Pool", group: "recreation", subcategory: "Swimming Pools", district: "Gasabo", area: "Nyarutarama" },
  { name: "Kigali Serena Hotel Pool", group: "recreation", subcategory: "Swimming Pools", district: "Nyarugenge", area: "Kiyovu" },
  { name: "WAKA Fitness Kimihurura", group: "recreation", subcategory: "Fitness Centers", district: "Gasabo", area: "Kimihurura" },
  { name: "WAKA Fitness Downtown", group: "recreation", subcategory: "Fitness Centers", district: "Nyarugenge", area: "Kigali City Centre" },

  /* ----------------------------------------------------------- nature */
  { name: "Rusumo Falls", group: "nature", subcategory: "Waterfalls", district: "Kirehe", description: "Falls on the Kagera River at the Tanzanian border." },
  { name: "Ndaba Falls", group: "nature", subcategory: "Waterfalls", district: "Karongi" },
  { name: "Isumo Waterfall", group: "nature", subcategory: "Waterfalls", district: "Nyamagabe", description: "Reached by a forest trail inside Nyungwe." },
  { name: "Congo Nile Trail", group: "nature", subcategory: "Hiking Trails", district: "Karongi", description: "Long-distance route along the shore of Lake Kivu." },
  { name: "Mount Bisoke Trail", group: "nature", subcategory: "Hiking Trails", district: "Musanze", description: "Day hike to a volcanic crater lake." },
  { name: "Mount Karisimbi Trail", group: "nature", subcategory: "Hiking Trails", district: "Musanze", description: "Rwanda's highest peak, usually a two-day climb." },
  { name: "Mount Muhabura Trail", group: "nature", subcategory: "Hiking Trails", district: "Burera" },
  { name: "Kamiranzovu Trail", group: "nature", subcategory: "Hiking Trails", district: "Nyamagabe" },
  { name: "Mount Kigali Trail", group: "nature", subcategory: "Hiking Trails", district: "Nyarugenge" },
  { name: "Lake Muhazi", group: "nature", subcategory: "Lakes", district: "Rwamagana" },
  { name: "Lake Ihema", group: "nature", subcategory: "Lakes", district: "Kayonza", description: "Akagera's largest lake, known for hippos and boat safaris." },
  { name: "Lake Mugesera", group: "nature", subcategory: "Lakes", district: "Ngoma" },
  { name: "Lake Rweru", group: "nature", subcategory: "Lakes", district: "Bugesera" },
  { name: "Rugezi Marsh", group: "nature", subcategory: "Nature Reserves", district: "Burera", description: "Protected wetland and important bird area." },
  { name: "Gishwati Forest", group: "nature", subcategory: "Forests", district: "Rutsiro" },
  { name: "Mukura Forest", group: "nature", subcategory: "Forests", district: "Rutsiro" },

  /* ---------------------------------------------------------- wonders */
  { name: "Virunga Volcanoes", group: "wonders", subcategory: "Natural Wonders", district: "Musanze", description: "The chain of volcanoes along Rwanda's northern border." },
  { name: "Nyungwe Canopy Walkway", group: "wonders", subcategory: "Tourist Attractions", district: "Nyamagabe", description: "Suspended walkway 50 metres above the forest floor." },
  { name: "Dian Fossey Tomb and Karisoke Trail", group: "wonders", subcategory: "Tourist Attractions", district: "Musanze" },
  { name: "Gorilla Guardians Village", group: "wonders", subcategory: "Tourist Attractions", district: "Musanze", description: "Community cultural experience beside Volcanoes National Park." },
  { name: "Akagera Boat Safari", group: "wonders", subcategory: "Tourist Attractions", district: "Kayonza" },
  { name: "Kigali Convention Centre Dome", group: "wonders", subcategory: "Landmarks", district: "Gasabo", area: "Kimihurura" },
  { name: "Kigali City Tower", group: "wonders", subcategory: "Landmarks", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Rebero Hill Viewpoint", group: "wonders", subcategory: "Scenic Viewpoints", district: "Kicukiro", area: "Rebero" },
  { name: "Karongi Lakeside Viewpoint", group: "wonders", subcategory: "Scenic Viewpoints", district: "Karongi" },
  { name: "Bisoke Crater Lake Viewpoint", group: "wonders", subcategory: "Scenic Viewpoints", district: "Musanze" },
  { name: "Camp Kigali Monument", group: "wonders", subcategory: "Monuments", district: "Nyarugenge", description: "Ten stone columns for the ten Belgian peacekeepers killed in 1994." },
  { name: "Nyanza Royal Monument", group: "wonders", subcategory: "Monuments", district: "Nyanza" },

  /* ----------------------------------------------------------- dining */
  { name: "Heaven Restaurant", group: "dining", subcategory: "Restaurants", district: "Nyarugenge", area: "Kiyovu" },
  { name: "Chez Lando", group: "dining", subcategory: "Restaurants", district: "Gasabo", area: "Remera" },
  { name: "Khana Khazana", group: "dining", subcategory: "Restaurants", district: "Nyarugenge", area: "Kiyovu" },
  { name: "Sole Luna", group: "dining", subcategory: "Restaurants", district: "Gasabo", area: "Kacyiru" },
  { name: "Bourbon Coffee — Kigali Heights", group: "dining", subcategory: "Cafés", district: "Gasabo", area: "Kimihurura" },
  { name: "Java House Rwanda", group: "dining", subcategory: "Cafés", district: "Gasabo", area: "Kimihurura" },
  { name: "Neo Cafe", group: "dining", subcategory: "Cafés", district: "Gasabo", area: "Kimihurura" },
  { name: "Shokola Cafe", group: "dining", subcategory: "Cafés", district: "Gasabo", area: "Kacyiru" },
  { name: "Envy Lounge", group: "dining", subcategory: "Bars", district: "Gasabo", area: "Kimihurura" },
  { name: "Riders Lounge Kigali", group: "dining", subcategory: "Bars", district: "Gasabo", area: "Kimihurura" },
  { name: "Cocobean", group: "dining", subcategory: "Resto Bars", district: "Gasabo", area: "Kimihurura" },

  /* ------------------------------------------------------------ stays */
  { name: "Kigali Serena Hotel", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Kiyovu" },
  { name: "Radisson Blu Hotel & Convention Centre", group: "stays", subcategory: "Hotels", district: "Gasabo", area: "Kimihurura" },
  { name: "Kigali Marriott Hotel", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Hôtel des Mille Collines", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Kiyovu" },
  { name: "Ubumwe Grande Hotel", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Lemigo Hotel", group: "stays", subcategory: "Hotels", district: "Gasabo", area: "Kacyiru" },
  { name: "M Hotel Kigali", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Onomo Hotel Kigali", group: "stays", subcategory: "Hotels", district: "Nyarugenge", area: "Nyarutarama" },
  { name: "Grand Legacy Hotel", group: "stays", subcategory: "Hotels", district: "Gasabo", area: "Kacyiru" },
  { name: "Bisate Lodge", group: "stays", subcategory: "Lodges", district: "Musanze", description: "Luxury eco-lodge beside Volcanoes National Park." },
  { name: "Sabyinyo Silverback Lodge", group: "stays", subcategory: "Lodges", district: "Musanze" },
  { name: "Five Volcanoes Boutique Hotel", group: "stays", subcategory: "Lodges", district: "Musanze" },
  { name: "Virunga Lodge", group: "stays", subcategory: "Lodges", district: "Burera" },
  { name: "Magashi Camp", group: "stays", subcategory: "Lodges", district: "Kayonza", description: "Tented camp in the north-east of Akagera." },
  { name: "Ruzizi Tented Lodge", group: "stays", subcategory: "Lodges", district: "Kayonza" },
  { name: "Akagera Game Lodge", group: "stays", subcategory: "Lodges", district: "Kayonza" },
  { name: "One&Only Nyungwe House", group: "stays", subcategory: "Lodges", district: "Nyamasheke" },
  { name: "Nyungwe Top View Hill Lodge", group: "stays", subcategory: "Lodges", district: "Nyamagabe" },
  { name: "Lake Kivu Serena Hotel", group: "stays", subcategory: "Resorts", district: "Rubavu", area: "Gisenyi" },
  { name: "Cleo Lake Kivu Hotel", group: "stays", subcategory: "Resorts", district: "Rubavu" },
  { name: "Mantis Kivu Marina Bay", group: "stays", subcategory: "Resorts", district: "Rubavu" },
  { name: "Moriah Hill Resort", group: "stays", subcategory: "Resorts", district: "Karongi" },
  { name: "Cormoran Lodge", group: "stays", subcategory: "Resorts", district: "Karongi" },
  { name: "Yambi Guesthouse", group: "stays", subcategory: "Guest Houses", district: "Gasabo", area: "Kacyiru" },
  { name: "Step Town Motel", group: "stays", subcategory: "Guest Houses", district: "Gasabo", area: "Remera" },
  { name: "Hotel Okapi", group: "stays", subcategory: "Guest Houses", district: "Nyarugenge" },
  { name: "Beausejour Hotel", group: "stays", subcategory: "Guest Houses", district: "Gasabo", area: "Remera" },
  { name: "Discover Rwanda Youth Hostel", group: "stays", subcategory: "Hostels", district: "Gasabo", area: "Kacyiru" },

  /* --------------------------------------------------------- shopping */
  { name: "Kigali City Tower Shops", group: "shopping", subcategory: "Malls", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "CHIC Building", group: "shopping", subcategory: "Malls", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "M Peace Plaza", group: "shopping", subcategory: "Malls", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Makuza Peace Plaza", group: "shopping", subcategory: "Malls", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Carrefour Kigali Heights", group: "shopping", subcategory: "Supermarkets", district: "Gasabo", area: "Kimihurura" },
  { name: "Sawa Citi", group: "shopping", subcategory: "Supermarkets", district: "Nyarugenge" },
  { name: "La Galette", group: "shopping", subcategory: "Supermarkets", district: "Nyarugenge", area: "Kiyovu" },
  { name: "Kimisagara Market", group: "shopping", subcategory: "Markets", district: "Nyarugenge", area: "Kimisagara" },
  { name: "Gisozi Market", group: "shopping", subcategory: "Markets", district: "Gasabo", area: "Gisozi" },
  { name: "Musanze Market", group: "shopping", subcategory: "Markets", district: "Musanze" },
  { name: "Huye Market", group: "shopping", subcategory: "Markets", district: "Huye" },
  { name: "Rubavu Market", group: "shopping", subcategory: "Markets", district: "Rubavu" },

  /* ---------------------------------------------------------- worship */
  { name: "Kigali Islamic Cultural Centre", group: "worship", subcategory: "Other Places of Worship", district: "Nyarugenge", area: "Nyamirambo" },
  { name: "Kigali Hindu Mandir", group: "worship", subcategory: "Temples", district: "Nyarugenge", area: "Kigali City Centre" },
  { name: "Sikh Gurudwara Kigali", group: "worship", subcategory: "Temples", district: "Nyarugenge" },
];
